### ISSUE TITLE
unable to pip install det

### ISSUE THREAD

**Issue by Gnoot01** [facebookresearch/sapiens#103]
Hi, I ran 'pip install -e . -v' in the det folder, and received this error. As you can see, I have the torch module indeed
```
\sapiens\sapiens-main\det> pip install -e . -v
Using pip 24.2 from C:\Users\Andrew\Desktop\Dev Me\TKR_model\1 calf raise\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\pip (python 3.10)
Obtaining file:///C:/Users/Andrew/Desktop/Dev%20Me/TKR_model/1%20calf%20raise/sapiens/sapiens-main/det
  Running command pip subprocess to install build dependencies
  Using pip 24.2 from C:\Users\Andrew\Desktop\Dev Me\TKR_model\1 calf raise\sapiens\sapiens-main\pose\demo\.venv\Lib\site-packages\pip (python 3.10)
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl.metadata
    Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
  Installing collected packages: setuptools
  Successfully installed setuptools-75.1.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Traceback (most recent call last):
    File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
    File "C:\Users\AppData\Local\Temp\pip-build-env-x7qx0rvj\overlay\Lib\site-packages\setuptools\build_meta.py", line 464, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
    File "C:\Users\AppData\Local\Temp\pip-build-env-x7qx0rvj\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "C:\Users\AppData\Local\Temp\pip-build-env-x7qx0rvj\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
      self.run_setup()
    File "C:\Users\AppData\Local\Temp\pip-build-env-x7qx0rvj\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\AppData\Local\Temp\pip-build-env-x7qx0rvj\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 17, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\sapiens\

sapiens-main\pose\demo\.venv\Scripts\python.exe' 'C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_editable 'C:\Users\AppData\Local\Temp\tmpxfb2driq'
  cwd: C:\Users\sapiens\sapiens-main\det
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
![a](https://github.com/user-attachments/assets/cc18daa7-fd8d-440f-b78c-e75bf175c228)

**Comment by Gnoot01** [comment]
Commenting out the following for bounding box detection does not work either, as there are other code dependent on it
```
parser.add_argument('det_config', help='Config file for detection')
parser.add_argument('det_checkpoint', help='Checkpoint file for detection')
```

**Comment by rawalkhirodkar** [comment]
Please comment out both det-config and det-checkpoint in the shell.

In that case, it is initialized to its default value.

On the error during install, the log says torch not found. Did you install pytorch before moving to det?

**Comment by rawalkhirodkar** [comment]
@Gnoot01 weird that the environment cannot find torch. Few options to try:
- do not install as editable. try `pip install .` instead of `pip install -e .`
- try without a detector, as suggested comment out det-config and det-checkpoint in the .sh or set them to empty string "".
- switch to another detector, modify the code to use another detector like [yolov9](https://github.com/ultralytics/ultralytics/blob/main/docs/en/models/yolov9.md).

**Comment by Gnoot01** [comment]
Does the included mmdet have to be be installed exactly?

I found this to work: 
```
pip install mmdet
pip install "mmcv>=2.0.0rc4,<2.2.0"
```

**Comment by Gnoot01** [comment]
However, now I get the following error

```
File "C:\Users\sapiens\sapiens-main\pose\demo\demo_vis.py", line 196, in main
    pose_estimator = init_pose_estimator(
  File "C:\Users\sapiens\sapiens-main\pose\mmpose\apis\inference.py", line 115, in init_model
    ckpt = load_checkpoint(model, checkpoint, map_location='cuda')
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\mmengine\runner\checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\mmengine\runner\checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\mmengine\runner\checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\mmengine\runner\checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\torch\serialization.py", line 1078, in load
    return torch.jit.load(opened_file, map_location=map_location)
  File "C:\Users\sapiens\sapiens-main\pose\demo\.venv\lib\site-packages\torch\jit\_serialization.py", line 165, in load
    cpp_module = torch._C.import_ir_module_from_buffer(
MemoryError: bad allocation
```

**Comment by RossLote** [comment]
@rawalkhirodkar 

Why was this closed? I'm having exactly the same issues and none of the above helps.

@Gnoot01 Did you get anywhere with this?
