### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by nitthilan** [facebookresearch/sapiens#107]
(sapiens_lite) nitthilan@LAPTOP-8MP3QC0P:/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/scripts/demo/torchscript$ ./depth.sh
Distributing 100 image paths into 1 jobs.
Path checkpoint  /mnt/d/nitthilan/reference/jasplay3d/sapiens/sapiens_lite_host/torchscript/depth/checkpoints/sapiens_0.6b/sapiens_0.6b_render_people_epoch_70_torchscript.pt2
Traceback (most recent call last):
  File "/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/demo/vis_depth.py", line 314, in <module>
    main()
  File "/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/demo/vis_depth.py", line 233, in main
    exp_model = exp_model.to(args.device)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 854, in _apply
    self._buffers[key] = fn(buf)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/scripts/demo/torchscript
Processing complete.
Results saved to /home/nitthilan/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_depth/sapiens_0.6b

Installation details:
 pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
 
 >>> torch.__version__
'2.4.1+cu124'
>>> print(torch.cuda.device_count())
1
>>>

Not sure why I get the above error. Any pointers on how to resolve this?

**Comment by rawalkhirodkar** [comment]
@nitthilan can you set the gpu_id here to 0? likely the process is picking up the wrong gpu device id.

**Comment by nitthilan** [comment]
I tried setting the gpu_id and the error still persists.

(sapiens_lite) nitthilan@LAPTOP-8MP3QC0P:/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/scripts/demo/torchscript$ **export CUDA_VISIBLE_DEVICES=0**
(sapiens_lite) nitthilan@LAPTOP-8MP3QC0P:/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/scripts/demo/torchscript$ ./depth.sh
Distributing 100 image paths into 1 jobs.
Path checkpoint  /mnt/d/nitthilan/reference/jasplay3d/sapiens/sapiens_lite_host/torchscript/depth/checkpoints/sapiens_0.6b/sapiens_0.6b_render_people_epoch_70_torchscript.pt2
**Debive id  cuda:0**
Traceback (most recent call last):
  File "/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/demo/vis_depth.py", line 315, in <module>
    main()
  File "/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/demo/vis_depth.py", line 234, in main
    exp_model = exp_model.to(args.device)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 854, in _apply
    self._buffers[key] = fn(buf)
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
  File "/home/nitthilan/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
/mnt/d/nitthilan/reference/jasplay3d/sapiens/lite/scripts/demo/torchscript
Processing complete.
Results saved to /home/nitthilan/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_depth/sapiens_0.6b

**Comment by nitthilan** [comment]
Just realized there is field in the script which sets the GPU ID. Setting it makes it work. Sorry for the confusion.

# JOBS_PER_GPU=1; TOTAL_GPUS=8; VALID_GPU_IDS=(0 1 2 3 4 5 6 7)
JOBS_PER_GPU=1; TOTAL_GPUS=1; VALID_GPU_IDS=(0)

**Comment by nitthilan** [comment]
Probably the VALID_GPU_IDS=(0) needs to be set to 0 by default instead of (2) as in the checked in code.
