### ISSUE TITLE
bfloat16 optimization not supported yet?

### ISSUE THREAD

**Issue by matabear-wyx** [facebookresearch/sapiens#113]
I tried to optimize my finetuned torch model to bf16, but the seg_optimizer.sh seems not working...

with the original script:
`W0925 10:49:49.446325 140679105111872 torch/_dynamo/convert_frame.py:762] [14/8] torch._dynamo hit config.cache_size_limit (8)
W0925 10:49:49.446325 140679105111872 torch/_dynamo/convert_frame.py:762] [14/8]    function: 'torch_dynamo_resume_in_new_func_at_367' (/home/wuyuxiong/yuxiong/sapiens/engine/mmengine/utils/misc.py:367)
W0925 10:49:49.446325 140679105111872 torch/_dynamo/convert_frame.py:762] [14/8]    last reason: ___check_obj_id(L['args'][0], 140661005003040)              
W0925 10:49:49.446325 140679105111872 torch/_dynamo/convert_frame.py:762] [14/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0925 10:49:49.446325 140679105111872 torch/_dynamo/convert_frame.py:762] [14/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
Graphs are not fusable. Expected 1 graph. Found 197`

with --force-compile:
`Traceback (most recent call last):
  File "/home/wuyuxiong/yuxiong/sapiens/seg/tools/deployment/torch_optimization.py", line 596, in <module>
    main()
  File "/home/wuyuxiong/yuxiong/sapiens/seg/tools/deployment/torch_optimization.py", line 585, in main
    compile_model(
  File "/home/wuyuxiong/yuxiong/sapiens/seg/tools/deployment/torch_optimization.py", line 244, in compile_model
    exported_model = torch.export.export(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/__init__.py", line 174, in export
    return _export(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/_trace.py", line 945, in wrapper
    raise e
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/_trace.py", line 928, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/exported_program.py", line 89, in wrapper
    return fn(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/_trace.py", line 1455, in _export
    aten_export_artifact = export_func(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/_trace.py", line 1060, in _strict_export
    gm_torch_level = _export_to_torch_ir(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/export/_trace.py", line 512, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1379, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 437, in call_function
    return tx.inline_user_function_return(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 437, in call_function
    return tx.inline_user_function_return(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 437, in call_function
    return tx.inline_user_function_return(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 437, in call_function
    return tx.inline_user_function_return(
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1459, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/wuyuxiong/yuxiong/miniconda3/envs/sapiens/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 477, in inner
    raise exc.UserError(
torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow. For more information about this error, see: https://pytorch.org/docs/main/generated/exportdb/index.html#cond-operands`

**Comment by rawalkhirodkar** [comment]
@matabear-wyx what pytorch version are you using? Our port to bfloat16 code is only tested with pytorch2.3 with A100.

**Comment by matabear-wyx** [comment]
> @matabear-wyx what pytorch version are you using? Our port to bfloat16 code is only tested with pytorch2.3 with A100.

I'm using pytorch 2.4 with H800

**Comment by rawalkhirodkar** [comment]
@matabear-wyx Thank you for the reply. The version/hardware mismatch might be the use. Please consider downgrading pytorch to 2.3 for porting to bfloat16. Alternatively, please use torchscript porting - which supports all gpus and pytorch2.2+.

**Comment by matabear-wyx** [comment]
> @matabear-wyx Thank you for the reply. The version/hardware mismatch might be the use. Please consider downgrading pytorch to 2.3 for porting to bfloat16. Alternatively, please use torchscript porting - which supports all gpus and pytorch2.2+.

OK, I'll try that! And yes, torchscript porting works for me.
