### ISSUE TITLE
 pose_keypoints133.sh got stuck in the lite demo. 

### ISSUE THREAD

**Issue by liuchanglab** [facebookresearch/sapiens#130]
When we run  pose_keypoints133.sh according to documents, it got stuck with no response. We have to kill the process, and it reports:

Traceback (most recent call last):
  File "/opt/tiger/sapiens/lite/demo/vis_pose.py", line 460, in <module>
    main()
  File "/opt/tiger/sapiens/lite/demo/vis_pose.py", line 391, in main
    pose_ops = pose_preprocess_pool.run(args_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tiger/sapiens/lite/demo/worker_pool.py", line 60, in run
    results = self.starmap(self.func, iterable, chunksize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/pool.py", line 765, in wait
    self._event.wait(timeout)
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
^CException ignored in atexit callback: <function _exit_function at 0x7fbbe3795b20>
Traceback (most recent call last):
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/util.py", line 334, in _exit_function
    _run_finalizers(0)
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/pool.py", line 732, in _terminate_pool
    p.join()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by rawalkhirodkar** [comment]
@liuchanglab please checkout https://github.com/facebookresearch/sapiens/issues/110
This is an issue due to incompatibility of parallelization with your hardware. Serializing the demo will resolve this.

**Comment by mlzxy** [comment]
This issue can be solved by adding 

```python
multiprocess.set_start_method('spawn')
```

to your main function.
