### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory while load mask

### ISSUE THREAD

**Issue by JV-X** [facebookresearch/sapiens#132]
after this issue( https://github.com/facebookresearch/sapiens/issues/120 )，i got a new error report:

```
1%|▊                                                                                  | 1/100 [00:01<02:52,  1.74s/it][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000000.npy'

  2%|█▋                                                                                 | 2/100 [00:02<02:02,  1.25s/it][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000001.npy'

  3%|██▍                                                                                | 3/100 [00:03<01:40,  1.03s/it][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000002.npy'

  4%|███▎                                                                               | 4/100 [00:04<01:29,  1.07it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000003.npy'

  5%|████▏                                                                              | 5/100 [00:04<01:22,  1.15it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000004.npy'

  6%|████▉                                                                              | 6/100 [00:05<01:18,  1.20it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000005.npy'

  7%|█████▊                                                                             | 7/100 [00:06<01:15,  1.24it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000006.npy'

  8%|██████▋                                                                            | 8/100 [00:07<01:13,  1.25it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000007.npy'

  9%|███████▍                                                                           | 9/100 [00:08<01:11,  1.27it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000008.npy'

 10%|████████▏                                                                         | 10/100 [00:08<01:10,  1.28it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000009.npy'

 11%|█████████                                                                         | 11/100 [00:09<01:09,  1.29it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000010.npy'

 12%|█████████▊                                                                        | 12/100 [00:10<01:08,  1.29it/s][ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/home/hygx/code/sapiens/lite/demo/worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "/home/hygx/code/sapiens/lite/demo/vis_depth.py", line 99, in img_save_and_viz
    mask = np.load(mask_path)
  File "/home/hygx/anaconda3/envs/sapiens_lite/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/hygx/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_2b/000011.npy'
```

How are these files generated that cannot be found?

thanks for your reply.

**Comment by rawalkhirodkar** [comment]
@JV-X we require segmentation mask (foreground/background) to normalize the predicted depth to 0 to 1 and visualize.
As mentioned in the readme, running segmentation first is a pre-requirement, please checkout: https://github.com/facebookresearch/sapiens/blob/main/lite/docs/DEPTH_README.md

**Comment by JV-X** [comment]
Does it mean that before I run ```./depth.sh```, I must run ```./seg.sh``` first?

**Comment by JV-X** [comment]
> @JV-X we require segmentation mask (foreground/background) to normalize the predicted depth to 0 to 1 and visualize. As mentioned in the readme, running segmentation first is a pre-requirement, please checkout: https://github.com/facebookresearch/sapiens/blob/main/lite/docs/DEPTH_README.md

Does it mean that before I run ```./depth.sh```, I must run ```./seg.sh``` first?

**Comment by rawalkhirodkar** [comment]
Yes.
