### ISSUE TITLE
Gotting GraalPy Error 

### ISSUE THREAD

**Issue by Mchapariniya** [facebookresearch/sapiens#139]
Hi!
After the previous issue I went through installing the conda.sh file. I tried many times with many different local and remote systems but every time I got this error:
<frozen graalpy.pip_hook>:48: RuntimeWarning: You are using an untested version of pip. GraalPy provides patches and workarounds for a number of packages when used with compatible pip versions. We recommend to stick with the pip version that ships with this version of GraalPy.
WARNING: There was an error checking the latest version of pip.
ERROR: Exception:
Traceback (most recent call last):
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 584, in wrapper
    result = user_function(*args, **kwds)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 49, in _iter_built
    for version, func in infos:
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 301, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 560, in wrapper
    result = user_function(*args, **kwds)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 883, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 560, in wrapper
    result = user_function(*args, **kwds)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/sources.py", line 194, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 784, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 448, in fetch_response
    return _get_index_content(location, session=self.session)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 352, in _get_index_content
    resp = _get_simple_response(url, session=session)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 131, in _get_simple_response
    resp = session.get(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/network/session.py", line 522, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/cachecontrol/adapter.py", line 76, in send
    resp = super().send(request, stream, timeout, verify, cert, proxies)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 105, in wrap_socket
    _verify_peercerts(ssl_sock, server_hostname=server_hostname)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 310, in _verify_peercerts
    cert_bytes = _get_unverified_chain_bytes(sslobj)
  File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 292, in _get_unverified_chain_bytes
    unverified_chain = sslobj.get_unverified_chain() or ()  # type: ignore[attr-defined]
AttributeError: '_SSLSocket' object has no attribute 'get_unverified_chain'
<frozen graalpy.pip_hook>:48: RuntimeWarning: You are using an untested version of pip. GraalPy provides patches and workarounds for a number of packages when used with compatible pip versions. We recommend to stick with the pip version that ships with this version of GraalPy.
WARNING: There was an error checking the latest version of pip.
<frozen graalpy.pip_hook>:48: RuntimeWarning: You are using an untested version of pip. GraalPy provides patches and workarounds for a number of packages when used with compatible pip versions. We recommend to stick with the pip version that ships with this version of GraalPy.
Using pip 24.2 from /home/masoumeh/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/site-packages/pip (python 3.10)
Obtaining file:///home/masoumeh/sapiens/cv
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/masoumeh/sapiens/cv/setup.py", line 16, in <module>
      import torch
    File "/home/masoumeh/anaconda3/envs/sapiens/lib/python3.10/site-packages/torch/__init__.py", line 749, in <module>
      raise ImportError(textwrap.dedent('''
  ImportError: Failed to load PyTorch C extensions:
      It appears that PyTorch has loaded the `torch/_C` folder
      of the PyTorch repository rather than the C extensions which
      are expected in the `torch._C` namespace. This can occur when
      using the `install` workflow. e.g.
          $ python setup.py install && python -c "import torch"

      This error can generally be solved using the `develop` workflow
          $ python setup.py develop && python -c "import torch"  # This should succeed
      or by running Python from a different directory.
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/masoumeh/anaconda3/envs/sapiens/bin/python -c '
  exec(compile('"'"''"'"''"'"'
 This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py

 - It imports setuptools before invoking setup.py, to enable projects that directly
   import from `distutils.core` to work with newer packaging standards.
 - It provides a clear error message when setuptools is not installed.
 - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    manifest_maker: standard file '"'"'-c'"'"' not found".
 - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/masoumeh/sapiens/cv/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-vmyti2kg
  cwd: /home/masoumeh/sapiens/cv/
  Preparing metadata (setup.py) ... error
WARNING: There was an error checking the latest version of pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Do you have any advice to solve the problem?

**Comment by rawalkhirodkar** [comment]
@Mchapariniya it seems you are a modified python env, graalpy. None of the installations should invoke this. Can you try with standard python?
