### ISSUE TITLE
TypeError: init_model() got an unexpected keyword argument 'override_ckpt_meta'

### ISSUE THREAD

**Issue by Zeyu-Zhu** [facebookresearch/sapiens#15]
Hi, thanks for the work.

I'm runing 'keypoints308.sh'. And this error occurred in '/pose/demo/demo_vis.py, line 193', I'd appreciate if you can help.

**Comment by rawalkhirodkar** [comment]
Hello, please follow the [conda.sh](https://github.com/facebookresearch/sapiens/blob/main/_install/conda.sh) for installation of dependencies. This will avoid version mismatch with third-party libraries.

**Comment by rawalkhirodkar** [comment]
Can you please share the entire error log?

**Comment by Zeyu-Zhu** [comment]
Installing additional Python packages...
<frozen graalpy.pip_hook>:48: RuntimeWarning: You are using an untested version of pip. GraalPy provides patches and workarounds for a number of packages when used with compatible pip versions. We recommend to stick with the pip version that ships with this version of GraalPy.
WARNING: There was an error checking the latest version of pip.
ERROR: Exception:
Traceback (most recent call last):
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 584, in wrapper
    result = user_function(*args, **kwds)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 49, in _iter_built
    for version, func in infos:
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 301, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 560, in wrapper
    result = user_function(*args, **kwds)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 883, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/jvm/languages/python/lib/python3.10/functools.py", line 560, in wrapper
    result = user_function(*args, **kwds)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/sources.py", line 194, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 784, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 448, in fetch_response
    return _get_index_content(location, session=self.session)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 352, in _get_index_content
    resp = _get_simple_response(url, session=session)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 131, in _get_simple_response
    resp = session.get(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_internal/network/session.py", line 522, in request
    return super().request(method, url, *args, **kwargs)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/cachecontrol/adapter.py", line 76, in send
    resp = super().send(request, stream, timeout, verify, cert, proxies)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 105, in wrap_socket
    _verify_peercerts(ssl_sock, server_hostname=server_hostname)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 310, in _verify_peercerts
    cert_bytes = _get_unverified_chain_bytes(sslobj)
  File "/workspace/zeyuzhu/anaconda3/envs/sapiens/lib/python3.10/site-packages/pip/_vendor/truststore/_api.py", line 292, in _get_unverified_chain_bytes
    unverified_chain = sslobj.get_unverified_chain() or ()  # type: ignore[attr-defined]
AttributeError: '_SSLSocket' object has no attribute 'get_unverified_chain'

**Comment by Zeyu-Zhu** [comment]
And I also found this: https://github.com/pypa/pip/issues/12892

**Comment by rawalkhirodkar** [comment]
This seems to be an error with your conda setup.

In this case, please try the minimal installation version of sapiens for inference, https://github.com/facebookresearch/sapiens/blob/main/lite/README.md

**Comment by Zeyu-Zhu** [comment]
I actually tried this https://github.com/facebookresearch/sapiens/blob/main/lite/README.md in the first place. But the error "TypeError: init_model() got an unexpected keyword argument 'override_ckpt_meta'" occurred. I'm wondering which version of mmpose is used?

**Comment by rawalkhirodkar** [comment]
Please use the lite scripts for inference. 
Click on the task links the lite readme for instructions.

**Comment by zxk19981227** [comment]
This problem becomes very interesting. No mmpose have this problem .This is a package from the mmpose directory in this project

**Comment by YejinHwang909** [comment]
Copying the `mmpose` folder from `/workspace/sapiens/pose` into the `demo` folder should resolve the issue!
