### ISSUE TITLE
Failed to build sapiens-cv

### ISSUE THREAD

**Issue by soltkreig** [facebookresearch/sapiens#164]
I have torch 2.4.1 + cuda 11.8 but cannot install sapiens-sv module. Any ideas?
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jovyan/shares/SR006.nfs2/people/murtazin/sapiens/cv/setup.py", line 452, in <module>
          setup(
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 664, in run
          self.run_command('build')
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/user/conda/envs/sapiens/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
          build_ext.build_extensions(self)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/user/conda/envs/sapiens/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/home/jovyan/.imgenv-murtazin-train1-0/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/home/user/conda/envs/sapiens/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/user/conda/envs/sapiens/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/user/conda/envs/sapiens/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
```

**Comment by soltkreig** [comment]
I found if I remove torch, cv module install:
```
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (2.4.0)
Requirement already satisfied: numpy in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (1.26.4)
Requirement already satisfied: packaging in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (24.2)
Requirement already satisfied: Pillow in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (11.0.0)
Requirement already satisfied: pyyaml in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (6.0.2)
Requirement already satisfied: yapf in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from sapiens-cv==1.0.0) (0.40.1)
Requirement already satisfied: platformdirs>=3.5.1 in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from yapf->sapiens-cv==1.0.0) (4.3.6)
Requirement already satisfied: tomli>=2.0.1 in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from yapf->sapiens-cv==1.0.0) (2.0.2)
Requirement already satisfied: importlib-metadata>=6.6.0 in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from yapf->sapiens-cv==1.0.0) (8.5.0)
Requirement already satisfied: zipp>=3.20 in /home/user/conda/envs/sapiens/lib/python3.10/site-packages (from importlib-metadata>=6.6.0->yapf->sapiens-cv==1.0.0) (3.21.0)
Building wheels for collected packages: sapiens-cv
  Building wheel for sapiens-cv (setup.py) ... done
  Created wheel for sapiens-cv: filename=sapiens_cv-1.0.0-py2.py3-none-any.whl size=725908 sha256=e30d84778d517240eaed17b3b1469f6fd2910f0e434799f7cdf0e53e1bc651c4
  Stored in directory: /tmp/pip-ephem-wheel-cache-immuwm54/wheels/8e/8a/a1/ca80e330519431f9c5211db9fac6b9ccf38ac5717e577f3e0a
Successfully built sapiens-cv
Installing collected packages: sapiens-cv
  Attempting uninstall: sapiens-cv
    Found existing installation: sapiens-cv 1.0.0
    Can't uninstall 'sapiens-cv'. No files were found to uninstall.
Successfully installed sapiens-cv-1.0.0
```

**Comment by soltkreig** [comment]
If I firstly install sapiens-cv then torch, I got this error:
```
Traceback (most recent call last):
  File "/home/jovyan/shares/SR006.nfs2/people/murtazin/sapiens/pose/demo/demo_vis_video_v3.py", line 356, in <module>
    main()
  File "/home/jovyan/shares/SR006.nfs2/people/murtazin/sapiens/pose/demo/demo_vis_video_v3.py", line 285, in main
    assert has_mmdet, 'Please install mmdet to run the demo.'
AssertionError: Please install mmdet to run the demo.
```

**Comment by rawalkhirodkar** [comment]
@soltkreig Please maintain the package installation order. torch -> cv -> other modules.
I see two python versions invocked 3.7 and 3.10 in your log. Are you using nested python envs?
Please consider installation in a new env with python 3.10+ from scractch.

**Comment by soltkreig** [comment]
Hi! The problem has been solved - because I use NFS to work, lib can doesn't compile on shared file systems.
