### ISSUE TITLE
Sapiens Lite Error: the length of kpt_color (133) does not matches that of keypoints (308)

### ISSUE THREAD

**Issue by wanghlsara** [facebookresearch/sapiens#30]
Awesome work!

I encountered an error when debugging Sapiens-Lite ：
```
100%|██████████| 96/96 [02:57<00:00,  1.68s/it][ERROR/SpawnPoolWorker-7] Traceback (most recent call last):
  File "C:\WORK\03.sapiens\lite\demo\worker_pool.py", line 20, in __call__
    result = self.__callable(*args, **kwargs)
  File "C:\WORK\03.sapiens\lite\demo\vis_pose.py", line 147, in img_save_and_viz
    raise ValueError(
ValueError: the length of kpt_color (133) does not matches that of keypoints (308)
```
The parameters I used were
```
python vis_pose.py C:\WORK\03.sapiens\lite\models\pose\checkpoints\sapiens_1b\sapiens_1b_goliath_best_goliath_AP_640_torchscript.pt2
--input C:\WORK\03.sapiens\pose\demo\data\baseball\img\image_list.txt
--output-root C:\WORK\03.sapiens\pose\demo\data\baseball\output
--num_keypoints 133
```
When I changed `--num_keypoints 133` to `--num_keypoints 308`, there were no more error messages, but the positions of the points drawn on the visualized image were incorrect. All the points were squeezed together, deviating from the human body.
May I ask where I went wrong and what should I do?

**Comment by rawalkhirodkar** [comment]
Please set --num_keypoints to 308.
