### ISSUE TITLE
Getting error while installing mmdet

### ISSUE THREAD

**Issue by VivekGuptaMatlab** [facebookresearch/sapiens#72]
I am getting error while installation of mmdet while running this command: cd $SAPIENS_ROOT/det; pip install -e .

This is the error I am getting:
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /home/brainbox/PycharmProjects/sapiens/det
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/brainbox/PycharmProjects/sapiens/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/brainbox/PycharmProjects/sapiens/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/brainbox/PycharmProjects/sapiens/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-oabez8gp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-oabez8gp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-oabez8gp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-oabez8gp/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I have checked with the flag `--use-pep517` and also try with installing without flag `-e`. Also, I have installed torch with CUDA support.

I am running sapiens in linux. This is the information about my linux: uname -a
Linux brainbox 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

This is the `nvidia-smi` output:
Wed Sep 11 18:57:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     Off | 00000000:01:00.0  On |                  Off |
|  0%   52C    P8              24W / 450W |   2680MiB / 24564MiB |     26%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1084      G   /usr/lib/xorg/Xorg                          324MiB |
|    0   N/A  N/A      1342      G   /usr/bin/gnome-shell                         67MiB |
|    0   N/A  N/A     18584      G   ...seed-version=20240909-180142.416000       62MiB |
|    0   N/A  N/A     21057      G   ...erProcess --variations-seed-version     2151MiB |
|    0   N/A  N/A     41420      G   ...yOnDemand --variations-seed-version       53MiB |
+---------------------------------------------------------------------------------------+

This is the output of `nvcc --version` output:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

This is the environment I am using:

addict==2.4.0
aliyun-python-sdk-core==2.15.2
aliyun-python-sdk-kms==2.16.5
appdirs==1.4.4
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
cityscapesScripts==2.2.3
click==8.1.7
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.0
crcmod==1.7
cryptography==43.0.1
cycler==0.12.1
Cython==3.0.11
fairscale==0.4.13
filelock==3.14.0
fonttools==4.53.1
fsspec==2024.2.0
humanfriendly==10.0
idna==3.8
imagecorruptions==1.1.2
imageio==2.35.1
importlib_metadata==8.4.0
Jinja2==3.1.3
jmespath==0.10.0
joblib==1.4.2
json-tricks==3.17.3
kiwisolver==1.4.7
lazy_loader==0.4
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
mmcv==2.0.1
mmdet==3.2.0
mmengine==0.10.4
model-index==0.1.11
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.1.105
nvidia-nvtx-cu12==12.1.105
opencv-python==4.10.0.84
opendatalab==0.0.10
openxlab==0.1.1
ordered-set==4.1.0
oss2==2.17.0
packaging==24.1
pandas==2.2.2
pillow==10.2.0
piq==0.8.0
platformdirs==4.3.2
pycocotools==2.0.8
pycparser==2.22
pycryptodome==3.20.0
Pygments==2.18.0
pyparsing==3.1.4
pyquaternion==0.9.9
python-dateutil==2.9.0.post0
pytz==2023.4
PyYAML==6.0.2
requests==2.28.2
rich==13.4.2
sapiens-det @ file:///home/brainbox/PycharmProjects/sapiens/det
-e git+https://github.com/facebookresearch/sapiens.git@f263bc9a2dc54d119f5c9a6b4e6d28ff310c2b39#egg=sapiens_cv&subdirectory=cv
-e git+https://github.com/facebookresearch/sapiens.git@f263bc9a2dc54d119f5c9a6b4e6d28ff310c2b39#egg=sapiens_engine&subdirectory=engine
scikit-image==0.24.0
scikit-learn==1.5.1
scipy==1.14.1
shapely==2.0.6
six==1.16.0
sympy==1.12
tabulate==0.9.0
termcolor==2.4.0
terminaltables==3.1.10
threadpoolctl==3.5.0
tifffile==2024.8.30
tomli==2.0.1
torch==2.4.1+cu121
torchaudio==2.4.1+cu121
torchvision==0.19.1+cu121
tqdm==4.65.2
triton==3.0.0
typing==3.7.4.3
typing_extensions==4.9.0
tzdata==2024.1
urllib3==1.26.20
yapf==0.40.2
zipp==3.20.1

Thanks in advance !!

**Comment by rawalkhirodkar** [comment]
@VivekGuptaMatlab as the error log says, please install pytorch first before proceeding to mmdet.
```ModuleNotFoundError: No module named 'torch'```

**Comment by VivekGuptaMatlab** [comment]
As I have provided the details of environment, I have the torch installed in my environment.

**Comment by Marc-3d** [comment]
i solved it by trying different versions of setuptools. This one happens to work: 

```
pip install setuptools==67
cd $SAPIENS_ROOT/det; pip install -e .
```

FYI, I am installing sapiens on a Google Cloud VM with Debian 11, in an anaconda environment with python 3.10.

**Comment by congsinfo** [comment]
I met similar issues when building a docker image. I tried adding `--no-build-isolation`, i.e. using `pip install --no-build-isolation -e .` to install mmdet. It works. FYI.
